name: Publish Release YAML

on:
  release:
    types: [created, published]

jobs:
  publish-release-yaml:
    name: Publish Release YAML
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4

      - name: Generate and upload release.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          tag=$(echo "${{ github.ref }}" | cut -c11-)  # get tag name without tags/refs/ prefix.
          ko resolve -t "${tag}" -f config/ > release.yaml
          gh release upload "${tag}" release.yaml
